#!/usr/bin/env bash
# ============================================================================
# tests/run.sh — Node test runner for the Mosaic Toolbox PJSR modules
# ============================================================================
#
# PixInsight scripts cannot run headless, so the strategy is:
#   1. strip the PixInsight preprocessor directives (#include, #define,
#      #feature-*, #engine, the #if family) from the module files — and ONLY
#      those, never JavaScript private class members like `#key()` or
#      `#buildGrid()`, which also begin with '#';
#   2. build tests/build/module.js: a shim for the PixInsight globals the pure
#      layer touches, the stripped modules concatenated in #include order, and a
#      module.exports block exposing the pure-logic functions under test;
#   3. syntax-check that exact file with `node --check`, then run every
#      tests/*.test.js against it;
#   4. syntax-check every PJSR file that is NOT bundled — the entry script and
#      the dialog, which builds PixInsight controls at load time — with the same
#      strip.
#
# What is covered here is the pure-logic layer: filter matching, robust
# statistics, identifier and coordinate formatting, the join layout and order,
# star merging, the MTF and the largest-covered-rectangle search, the data
# model's validation, and the English/French catalogue. The image, astrometry
# and GUI halves are exercised by hand in PixInsight — see docs/RELEASING.md.
#
# Usage: bash tests/run.sh
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/tests/build"
MODULE="$BUILD/module.js"
MT="$ROOT/pjsr/mosaictoolbox"

# Modules the harness loads and drives, in #include (dependency) order. Every
# one of these defines its functions and classes over a light shim and loads
# without a real PixInsight. MT_Dialog is excluded: it is `class ... extends
# Dialog`, which evaluates the base class at load time and cannot load here.
LIBS=(
   "$MT/MT_Lang.js"
   "$MT/MT_Globals.js"
   "$MT/MT_Data.js"
   "$MT/MT_Astrometry.js"
   "$MT/MT_Overlap.js"
   "$MT/MT_Photometry.js"
   "$MT/MT_Gradient.js"
   "$MT/MT_Join.js"
   "$MT/MT_Engine.js"
)

# Files the harness only parses.
UNBUNDLED=(
   "$ROOT/pjsr/MosaicToolbox.js"
   "$MT/MT_Dialog.js"
)

# Strip PixInsight preprocessor directives — and only those. The keyword list is
# explicit precisely so that a private class member (`#key`, `#writeB`,
# `#buildGrid`, `#readS`) is never mistaken for a directive and deleted. Handles
# backslash-continued directives (the entry's #feature-info) and CR endings.
strip() {
   sed -e 's/#__FILE__/"__FILE__"/g' "$1" |
      awk '
         { sub( /\r$/, "" ) }
         cont { cont = /\\$/; next }
         /^[[:space:]]*#(include|define|undef|ifndef|ifdef|elif|endif|else|if|feature-id|feature-info|feature-icon|engine|script-id|pragma|error|warning|import|target)([[:space:]]|<|"|$)/ {
            cont = /\\$/; next
         }
         { print }
      '
}

mkdir -p "$BUILD"

{
   echo '// Generated by tests/run.sh — do not edit'
   cat "$ROOT/tests/shim.js"
   for lib in "${LIBS[@]}"; do
      echo "// ---- $(basename "$lib") ----"
      strip "$lib"
   done
   cat <<'EOF'

module.exports = {
   // --- language ---------------------------------------------------------
   MT_LANGUAGES: MT_LANGUAGES,
   mtSetLanguage: mtSetLanguage,
   mtLanguage: mtLanguage,
   mtT: mtT,
   mtTv: mtTv,
   mtCatalogue: mtCatalogue,

   // --- globals: identity, filters, stats, identifiers, enums, coords ----
   MT_TITLE: MT_TITLE,
   MT_VERSION: MT_VERSION,
   MT_STANDARD_FILTERS: MT_STANDARD_FILTERS,
   MT_UNASSIGNED: MT_UNASSIGNED,
   mtNormaliseFilter: mtNormaliseFilter,
   mtMatchStandardFilter: mtMatchStandardFilter,
   mtSanitiseId: mtSanitiseId,
   mtUniqueId: mtUniqueId,
   mtMedian: mtMedian,
   mtMAD: mtMAD,
   mtMean: mtMean,
   mtEnumItems: mtEnumItems,
   mtEnumValue: mtEnumValue,
   mtInterpolationItems: mtInterpolationItems,
   mtProjectionItems: mtProjectionItems,
   mtInterpolationValue: mtInterpolationValue,
   mtProjectionValue: mtProjectionValue,
   mtFormatRA: mtFormatRA,
   mtFormatDec: mtFormatDec,

   // --- data model -------------------------------------------------------
   MT_Image: MT_Image,
   MosaicToolboxData: MosaicToolboxData,

   // --- photometry: the pure pieces --------------------------------------
   mtMergeStars: mtMergeStars,
   mtLinearLimit: mtLinearLimit,
   MT_LINEAR_FRACTION: MT_LINEAR_FRACTION,
   MT_LINEAR_FLOOR: MT_LINEAR_FLOOR,

   // --- astrometry: the pure pieces --------------------------------------
   mtMTF: mtMTF,
   mtLargestCoveredRect: mtLargestCoveredRect,

   // --- engine: layout and join order ------------------------------------
   mtIntersectionArea: mtIntersectionArea,
   mtUnionTileRect: mtUnionTileRect,
   mtCluster: mtCluster,
   mtOrderByConnectivity: mtOrderByConnectivity,
   mtPixelSizeForResolution: mtPixelSizeForResolution,
   mtDescribeLayout: mtDescribeLayout,

   // --- shim handles, for driving the above ------------------------------
   mtTestSetViews: mtTestSetViews,
   mtTestConsole: mtTestConsole,
   mtTestConsoleReset: mtTestConsoleReset
};
EOF
} > "$MODULE"

node --check "$MODULE"
echo "OK   syntax (node --check, bundled)"

for src in "${UNBUNDLED[@]}"; do
   out="$BUILD/check-$(basename "$src")"
   { echo "// Generated by tests/run.sh — do not edit"; strip "$src"; } > "$out"
   node --check "$out"
   echo "OK   syntax $(basename "$src") (node --check, unbundled)"
done

failures=0
total=0
for t in "$ROOT"/tests/*.test.js; do
   if node "$t" > "$BUILD/last.log" 2>&1; then
      # A zero exit is necessary but not sufficient. The suite must also have
      # said how many assertions it ran, in the exact form report() emits: a
      # suite that stopped asserting, or returned early, exits 0 with nothing to
      # show, and that must not read as success.
      summary="$(grep -E '^[a-z0-9_-]+: [0-9]+ assertions passed\.$' "$BUILD/last.log" | tail -1)"
      if [ -z "$summary" ]; then
         echo "FAIL $(basename "$t") exited 0 without reporting an assertion count"
         cat "$BUILD/last.log"
         failures=1
         continue
      fi
      n="$(printf '%s' "$summary" | grep -oE '[0-9]+ assertions' | grep -oE '[0-9]+')"
      total=$(( total + n ))
      echo "OK   $summary"
   else
      echo "FAIL $(basename "$t")"
      cat "$BUILD/last.log"
      failures=1
   fi
done

if [ "$failures" -ne 0 ]; then
   echo "Tests failed." >&2
   exit 1
fi
echo "All tests passed ($total assertions)."
